// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA46_kuIhjr7X1KFKPx62Uw_R1oVfpSK0o',
    appId: '1:789414407702:web:25c74a039748e09805cf37',
    messagingSenderId: '789414407702',
    projectId: 'busapp-a300a',
    authDomain: 'busapp-a300a.firebaseapp.com',
    storageBucket: 'busapp-a300a.firebasestorage.app',
    measurementId: 'G-RJCB1MW47P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHDsndnVWiXidv8cwk8DQ8HcYrxDequn0',
    appId: '1:789414407702:android:299819390bd4b84505cf37',
    messagingSenderId: '789414407702',
    projectId: 'busapp-a300a',
    storageBucket: 'busapp-a300a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYKWVSR9JapRYQTcJUdgT_fnFPU2IqZcQ',
    appId: '1:789414407702:ios:6c667e61f40613ef05cf37',
    messagingSenderId: '789414407702',
    projectId: 'busapp-a300a',
    storageBucket: 'busapp-a300a.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYKWVSR9JapRYQTcJUdgT_fnFPU2IqZcQ',
    appId: '1:789414407702:ios:6c667e61f40613ef05cf37',
    messagingSenderId: '789414407702',
    projectId: 'busapp-a300a',
    storageBucket: 'busapp-a300a.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA46_kuIhjr7X1KFKPx62Uw_R1oVfpSK0o',
    appId: '1:789414407702:web:2a551c6183db6eeb05cf37',
    messagingSenderId: '789414407702',
    projectId: 'busapp-a300a',
    authDomain: 'busapp-a300a.firebaseapp.com',
    storageBucket: 'busapp-a300a.firebasestorage.app',
    measurementId: 'G-82KM6M8Y26',
  );
}
